# Generated by Django 4.0.5 on 2022-07-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_configuration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='category',
            new_name='parent_field',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='parent_xpath',
        ),
        migrations.AddField(
            model_name='configuration',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='configuration',
            constraint=models.UniqueConstraint(fields=('scheme_name', 'field'), name='unique_set'),
        ),
    ]
