# Generated by Django 4.0.5 on 2022-07-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_category_configuration_parent_field_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='configuration',
            name='unique_set',
        ),
        migrations.AddConstraint(
            model_name='configuration',
            constraint=models.UniqueConstraint(fields=('scheme_name', 'field', 'parent_field'), name='unique_set'),
        ),
    ]
