# Generated by Django 4.0.5 on 2022-07-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_configuration_unique_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
